### ISSUE TITLE
SQL Developer access

### ISSUE THREAD

**Issue by yachtsman60** [gotsysdba/oci-arch-apex-vanity#1]
Hi, as the ADB has a private IP address that is only accessible from clients and hosts that are located within, or have access to, the virtual cloud network (VCN) used by the Autonomous Database. How can we enable SQL Developer access from a developers laptop? We have downloaded the wallet but clearly SQL Dev fails to find the URL in the tnsnames.ora file. Do we need to create a VPN link to the OCI tenancy?
Many thanks

**Comment by gotsysdba** [comment]
Hello, I've updated the [FAQ](https://github.com/gotsysdba/oci-arch-apex-vanity/blob/main/FAQS.md) with your question and a few options.  Hope that helps.
